<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>FaceAPI.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.bak.cs" />
    <Compile Remove="RecognitionModelVersion.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.CognitiveServices.Vision.Face" Version="2.8.0-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net6.0\" />
  </ItemGroup>

</Project>
